/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as ForResearchersRouteImport } from './routes/for/researchers'
import { Route as ForLegalRouteImport } from './routes/for/legal'
import { Route as DocsSlugRouteImport } from './routes/docs/$slug'
import { Route as ApiModelsRouteImport } from './routes/api/models'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForResearchersRoute = ForResearchersRouteImport.update({
  id: '/for/researchers',
  path: '/for/researchers',
  getParentRoute: () => rootRouteImport,
} as any)
const ForLegalRoute = ForLegalRouteImport.update({
  id: '/for/legal',
  path: '/for/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/docs/$slug',
  path: '/docs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelsRoute = ApiModelsRouteImport.update({
  id: '/api/models',
  path: '/api/models',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/api/models': typeof ApiModelsRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/for/legal': typeof ForLegalRoute
  '/for/researchers': typeof ForResearchersRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/api/models': typeof ApiModelsRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/for/legal': typeof ForLegalRoute
  '/for/researchers': typeof ForResearchersRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/api/models': typeof ApiModelsRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/for/legal': typeof ForLegalRoute
  '/for/researchers': typeof ForResearchersRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/api/models'
    | '/docs/$slug'
    | '/for/legal'
    | '/for/researchers'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/api/models'
    | '/docs/$slug'
    | '/for/legal'
    | '/for/researchers'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/api/models'
    | '/docs/$slug'
    | '/for/legal'
    | '/for/researchers'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  ApiModelsRoute: typeof ApiModelsRoute
  DocsSlugRoute: typeof DocsSlugRoute
  ForLegalRoute: typeof ForLegalRoute
  ForResearchersRoute: typeof ForResearchersRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for/researchers': {
      id: '/for/researchers'
      path: '/for/researchers'
      fullPath: '/for/researchers'
      preLoaderRoute: typeof ForResearchersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for/legal': {
      id: '/for/legal'
      path: '/for/legal'
      fullPath: '/for/legal'
      preLoaderRoute: typeof ForLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/docs/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/models': {
      id: '/api/models'
      path: '/api/models'
      fullPath: '/api/models'
      preLoaderRoute: typeof ApiModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  ApiModelsRoute: ApiModelsRoute,
  DocsSlugRoute: DocsSlugRoute,
  ForLegalRoute: ForLegalRoute,
  ForResearchersRoute: ForResearchersRoute,
  DocsIndexRoute: DocsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
